# Generated by Django 5.2.12 on 2026-04-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
        ('users', '0003_repository_snap_threadmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexer_repositories', to='users.userprofile'),
        ),
    ]
