# Generated by Django 5.2.12 on 2026-04-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_alter_repository_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='indexer.snap')),
            ],
        ),
    ]
